# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test-8-29' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test-8-29
pod "PGFramework"
  target 'Test-8-29Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test-8-29UITests' do
    # Pods for testing
  end

end
